---
layout: post
title: "Совместный доступ к ресурсам в Django"
date: 2011-11-15
comments: false
categories:
 - sciencewise
 - django
 - concurrency
---


Ну вот наконец-то наш <a href="http://sciencewise.info/">проект</a> и дорос до состояния, когда стали возникать ошибки совместного доступа к ресурсам.<br /><br />Первой ласточкой стала <b>IOError </b>(CRC check failed), которая возникла когда один процесс начал закачивать архив статьи, а другой, подумав что архив уже скачан, принялся его старательно распаковывать.<br /><br />Как раз для таких случаев в Django есть специальный декоратор:&nbsp;<a href="https://docs.djangoproject.com/en/dev/topics/db/transactions/#controlling-transaction-management-in-views">@transaction.commit_on_success</a>&nbsp;(в Django 1.3 его также можно использовать как <b>context manager</b>). Просто добавляем его к функции, и при любом возникшем внутри функции исключении (например IOError), функция будет завершаться, не сохраняя никаких измнений в базу.</div>
